### ISSUE TITLE
Restrict by IP

### ISSUE THREAD

**Issue by siimsoni** [symphonycms/debugdevkit#44]
I have been using Symphony CMS for a bit, and I'm very happy with it and especially the debug devkit makes it much easier to see what's going on under the hood.

I'm somewhat concerned however that when the devkit is enabled, then every visitor can use it. Although usually there isn't much special there, it still worries me as it reveals quite a lot what's going on under the hood; usually very useful for hackers.

So I have a little request that there could be a possibility to limit what IP addresses can use the debug functionality. Especially there should be very easy way to use the specify the current IP address.

My only concern is that this feature could induce some sort of "feature creep", so I'm not sure if it should be a part of this project; should it be some fork or another extension? What's your thoughts?

**Comment by michael-e** [comment]
As the README says, the devkit will only work if you are logged in to Symphony. Do you think that this is not sufficient?

**Comment by nitriques** [comment]
@siimsoni as @michael-e said, only logged user can access it. If that's not enough for you, you can add a rewrite rule in the .htaccess to deny access by ip.

See http://stackoverflow.com/questions/1073852/mod-rewrite-based-on-ip

**Comment by siimsoni** [comment]
Thanks @michael-e and @nitriques. I had somehow missed that only logged in users can use this functionality.

**Comment by michael-e** [comment]
:-)

**Comment by nitriques** [comment]
@siimsoni It would have been a REALLY bad thing from our part to not have caught this earlier ;)

I had a client that wanted this kind of feature and the .htaccess config worked like a charm. Also, any paths starting with `/symphony` are denied.
